### ISSUE TITLE
Not resizing properly in i3

### ISSUE THREAD

**Issue by matiuri** [daa84/neovim-gtk#58] opened 2018-02-13 23:28 UTC
When launching neovim-gtk from terminal in tiling mode, it will consider the size of the previous instance, instead of the size of this instance's window. As a result of this, the airline-tabline on the top won't be shown unless I exit neovim-gtk and relaunch it to be on the exact same size as before.
Furthermore, if I last opened it in a small tile, when I open it again in full screen mode, it will be shown as in the picture.
![captura de pantalla de 2018-02-13 20-40-54](https://user-images.githubusercontent.com/11176122/36180233-4e16cad2-10fe-11e8-8a76-b7fef7a4bf9c.png)

I don't know if this error is related: `ERROR:<unknown>: Error while reading: I/O error while reading marker byte: failed to fill whole buffer`. It's shown every time I close with `:q`.

**Comment by daa84** [comment] 2018-02-15 10:16
Default window size stored when window close and then sets with `gtk_window_set_default_size`. But later change must generate `configure-event` that will change content size. Looks like for some reason resize event does not generate configure-event, but set_default_size generates.

Can't say how to debug this on default ubuntu

**Comment by daa84** [comment] 2018-02-15 10:17
Maybe just add some key to disable size saving

**Comment by matiuri** [comment] 2018-02-15 10:37
I don't get it. Should I disable size saving? If so, how?

**Comment by daa84** [comment] 2018-02-16 08:53
I think i can add new option to disable size saving

**Comment by Zardoz89** [comment] 2018-02-16 09:15
I don't know if is related, but I can't resize anymore nvim-gtk window, using the window borders.
The only way that It works, is if I do right click on the app title bar and select "resize option"

**Comment by daa84** [comment] 2018-02-16 10:04
added --disable-win-restore option, you can try it, if this solve this issue.

**Comment by matiuri** [comment] 2018-02-16 10:44
When I open neovim-gtk with that parameter inside an empty working space, it'll mostly show as in the first picture, and rarely as in the second one.
![captura de pantalla de 2018-02-16 07-36-06](https://user-images.githubusercontent.com/11176122/36303991-d894101c-12ec-11e8-8b13-897eee4530fc.png)
![captura de pantalla de 2018-02-16 07-35-33](https://user-images.githubusercontent.com/11176122/36304027-f90123ee-12ec-11e8-8220-eafc0820d5bb.png)

*Note on the first picture: it seems that neovim might be rendering a bit out of frame, as my top bar is not showing and the bottom black space is too big.*

**Comment by unclechu** [comment] 2018-02-16 21:33
I have kinda like this issue with i3 too. Sometimes it just gets wrong height, and last command line is shifted behind visible part of the window. When it happens I'm usually toggle fullscreen mode to fix it. And this issue appeared after some commits about "window resize" (sad but I don't remember exact one).

**Comment by matiuri** [comment] 2018-02-16 21:48
@unclechu Do you have the same problem with Airline's buffer line, too?

**Comment by daa84** [comment] 2018-02-17 10:12
Can't say how to debug this.
I add ability to log messages for resize events in latest commit.
Please run it like `RUST_LOG=nvim_gtk::shell cargo run`
Also some questions:
* neovim version?
* is tabline disabled/enabled?
Please past logs from above command here. First reproduce error, then past logs.
Maybe latest/ not stable neovim does not have such error?

**Comment by matiuri** [comment] 2018-02-17 10:58
Neovim version: 0.2.2
#### If neovim-gtk's tabline is enabled:
![captura de pantalla de 2018-02-17 07-45-22](https://user-images.githubusercontent.com/11176122/36340209-ebe7841c-13b6-11e8-828f-58eb5753542c.png)
*The only case on which I can see Airline's buffers bar*
```
DEBUG 2018-02-17T10:44:59Z: nvim_gtk::shell: Init nvim 100/40
DEBUG 2018-02-17T10:44:59Z: nvim_gtk::shell: configure_event (800, 600)
DEBUG 2018-02-17T10:44:59Z: nvim_gtk::shell: configure_event (1916, 1046)
DEBUG 2018-02-17T10:44:59Z: nvim_gtk::shell: on_resize 100/40
```

![captura de pantalla de 2018-02-17 07-53-46](https://user-images.githubusercontent.com/11176122/36340244-b2f30450-13b7-11e8-876b-99657ee804b6.png)
```
DEBUG 2018-02-17T10:44:52Z: nvim_gtk::shell: Init nvim 100/40
DEBUG 2018-02-17T10:44:52Z: nvim_gtk::shell: configure_event (800, 600)
DEBUG 2018-02-17T10:44:52Z: nvim_gtk::shell: configure_event (1916, 1046)
DEBUG 2018-02-17T10:44:53Z: nvim_gtk::shell: ui_try_resize 239/69
DEBUG 2018-02-17T10:44:53Z: nvim_gtk::shell: on_resize 100/40
DEBUG 2018-02-17T10:44:53Z: nvim_gtk::shell: on_resize 239/69
```

#### If neovim-gtk's tabline is disabled:
![captura de pantalla de 2018-02-17 07-52-08](https://user-images.githubusercontent.com/11176122/36340237-898fbdce-13b7-11e8-8803-55414a4d740e.png)
*The line's number is moved to the text section*
```
DEBUG 2018-02-17T10:51:16Z: nvim_gtk::shell: Init nvim 100/40
DEBUG 2018-02-17T10:51:16Z: nvim_gtk::shell: configure_event (800, 600)
DEBUG 2018-02-17T10:51:17Z: nvim_gtk::shell: configure_event (1916, 1046)
DEBUG 2018-02-17T10:51:17Z: nvim_gtk::shell: ui_try_resize 239/69
DEBUG 2018-02-17T10:51:17Z: nvim_gtk::shell: on_resize 100/40
DEBUG 2018-02-17T10:51:17Z: nvim_gtk::shell: on_resize 239/69
DEBUG 2018-02-17T10:51:17Z: nvim_gtk::shell: on_resize 239/69
```

**Comment by unclechu** [comment] 2018-02-18 14:23
@matiuri 
> Do you have the same problem with Airline's buffer line, too?

No I don't, but it may be just because I usually don't have vertically split windows along with *neovim-gtk* window, so I haven't faced issue with window width (only with height).

**Comment by unclechu** [comment] 2018-02-18 14:44
I found a way to reproduce it properly. I can reproduce it on latest commit: 8bf342ec7f6b0bc0f0877d62a491d4322f9ce266

1. Open `nvim-gtk`
2. Open *vim-ctrlspace* window and close it
3. One bottom line is shifted
4. Toggle fullscreen mode twice (X11 fullscreen, i3 key hook)
5. After this the issue won't appear anymore

Also if I toggle fullscreen just after `nvim-gtk` started this issue also won't appear.
Screencast: https://youtu.be/Kn0G479SAuE

I just realized also that top airline line is also behind the screen after start.

**Comment by matiuri** [comment] 2018-02-18 15:26
Now the line's number will always be in the text section until I resize the window or create a new line.
![captura de pantalla de 2018-02-18 12-18-51](https://user-images.githubusercontent.com/11176122/36353486-e77762f4-14a5-11e8-9f4b-3ec2737401b2.png)

**Comment by daa84** [comment] 2018-02-19 10:06
please try it with latest commit

**Comment by matiuri** [comment] 2018-02-19 10:23
Same problem with 7e857a1. And yes, the last screenshot was on 8bf342e.

**Comment by matiuri** [comment] 2018-02-19 10:33
When neovim-gtk starts, everything is OK. Then, on first resize to fill the window, Airline's buffer bar disappear. Finally, on second resize to assure it fills the whole window, the line's number is tabbed. After that, toggling fullscreen on and off will solve everything but Airline's buffer bar, which won't show again.

**Comment by unclechu** [comment] 2018-02-20 19:15
I have this fixed with f9b20db.

**Comment by daa84** [comment] 2018-02-21 09:33
Looks like there two bugs, 
1. resize does not happens at all,
2. some problems with layout after resize

so looks like 1 is fixed and 2. not?
second question can it be that 2. is not problem of neovim-gtk, but more neovim + some plugin configuration?

**Comment by unclechu** [comment] 2018-02-22 10:17
Now with f9b20db I have this:
Look, when I execute this function:
https://github.com/unclechu/neovimrc/blob/fe6326a/my-modules/background-toggle.vim#L4-L10
I have this (see short screencast): https://youtu.be/qWcNBoq4R0Y
I have broken size of screen and left-top part of airline at the bottom of the screen, only fullscreen toggle heals it. But when I recorded screencast, second time, I couldn't reproduce issue with wrong size, in previous try I had right-top part of airline behind the screen (expanded about 1 column) and bottom line behind the screen too. In TUI it's okay.

**Comment by daa84** [comment] 2018-02-23 09:51
Hmm, ok, time to time I also can reproduce this, without timeout - this was much more times, but with timeout this also happens sometimes.

**Closed** 2018-02-23 10:07 UTC
