### ISSUE TITLE
Subpixel Font Rendering

### ISSUE THREAD

**Issue by landersson** [daa84/neovim-gtk#169] opened 2019-01-09 02:30 UTC
Hi,

I seem to have a minor issue with LCD subpixel rendering in nvim-gtk. Compared to the font rendering in gvim, using the same font, the quality is slightly better in gvim. It looks like LCD subpixel font rendering is not configured properly in nvim-gtk.

gvim:

![gvim](https://user-images.githubusercontent.com/2536670/50871981-afec2880-1411-11e9-9e9e-50c1788b2dd5.png)

nvim-gtk:
![nvim-gtk](https://user-images.githubusercontent.com/2536670/50872028-ef1a7980-1411-11e9-893f-b36f88c96d80.png)

It looks like there is some minor LCD subpixel rendering happening even when using nvim-gtk, but much less than when using gvim, and the rgb order also seem to be reversed.

Any idea how to fix this? Would it be possible to use cairo::FontOptions to enforce specific font rendering options to see it that helps?

gtk-rs.org/docs/cairo/struct.FontOptions.html

**Comment by landersson** [comment] 2019-01-11 01:35
I think the issue could somehow be related to the text renderer not being aware of the current background colour. Subpixel rendering works fine with a dark background.

Could this be related to the transparency support?

**Comment by daa84** [comment] 2019-01-12 09:06
Yes it can be, rendering works with layers that combines together. So maybe white background combined with transparency rendered pixel gives this strange result.

**Comment by landersson** [comment] 2019-01-12 11:07
I haven't enabled background transparency though, unless it's somehow enabled by default.

Is there an easy way to definitively disable transparency?

**Comment by daa84** [comment] 2019-01-12 19:10
This is not transparency background problem, but problem of compositing, background color composed with text with CAIRO_OPERATOR_OVER: so resulting color in case it transparent changed as `(xaA + xaB·(1−aA))/aR`.

**Comment by daa84** [comment] 2019-01-12 20:39
Correction: CAIRO_OPERATOR_DEST used, but that for some unknown (for me) reason do color modification of dest. Think i can try to use surface instead of group, maybe this helps

**Comment by landersson** [comment] 2019-01-13 23:57
To me, it definitively looks related to subpixel antialiasing though. It's only the pixels where the text renderer attempts to do subpixel correction that look wrong.

**Comment by mcepl** [comment] 2019-01-16 11:20
Just to note, it looks like a duplicate of #88. Still reproducible with build from 7cda84c.
![nvim-gtk-anti-aliasing](https://user-images.githubusercontent.com/198999/51245848-20062b80-1989-11e9-83d9-5b96198c9e80.png)

**Comment by landersson** [comment] 2019-01-16 22:55
@mcepl, I don't think these are identical issues. Looking closer at your images, your font rendering doesn't seem to use LCD subpixel antialiasing at all (i.e, you don't have the blue/red fringe pixels around letters as seen in my example images). My main issue is that the subpixel correction seem to assume a dark background.

**Comment by daa84** [comment] 2019-01-20 12:12
@landersson can you check branch subpixel_render_fix? Does it fix your issue?
Maybe it introduce some new :smile:

**Comment by landersson** [comment] 2019-01-20 22:56
Yep, this seem to fix the issue... fonts now look as good as in gvim, and nvim-gtk is quite a bit snappier. Thanks!

![nvim-fixed](https://user-images.githubusercontent.com/2536670/51446164-56b1bc80-1d62-11e9-9e78-8050b61b4439.png)

I haven't looked carefully, but I haven't noticed anything else breaking.

**Closed** 2019-01-21 14:17 UTC
