### ISSUE TITLE
Spanish accents are not shown

### ISSUE THREAD

**Issue by jorrete** [daa84/neovim-gtk#6] opened 2017-05-30 20:19 UTC
Hi,
I am using a spanish layout and the keys are in the right place but accents don't appear.
Usually to set an accent in a letter "a" - "á", you have to press the accent key and the the letter.
It seems that that combination is not working.

**Comment by daa84** [comment] 2017-05-31 14:20
Looks like this can be fixed by implementing GtkImContext support. This is in my plan 😄

**Comment by jorrete** [comment] 2017-10-18 07:44
Hi,
I still can not user accents as per today's build.
Thanks.

**Comment by daa84** [comment] 2017-10-18 14:53
Can you provide details? OS and the actual layout settings.

**Comment by RoGryza** [comment] 2017-11-07 13:27
Getting the same problem on arch using the aur `neovim-gtk-git` package

**Comment by felmab** [comment] 2017-12-01 09:44
In the meantime, you can use [digraphs](http://vimdoc.sourceforge.net/htmldoc/digraph.html), for instance ^K + a + ' to insert á.

**Comment by daa84** [comment] 2017-12-01 14:01
Ok, what i do: 
1. set composite key in gnome settings to rwin
2. run neovim-gtk 
3. press `rwin+a '`

for me it works and inserts á
i find that behavior changed when GTK_IM_MODULE is changed
`echo $GTK_IM_MODULE` show me `ibus`.

So to reproduce problem i need more details on actual keyboard layout settings.

**Comment by felmab** [comment] 2017-12-01 14:33
I use the Archlinux package, my window manager is Awesome. Compose key is set to ralt in /etc/X11/xorg.conf.d/10-evdev.conf. My keyboard layout is mainly standard QWERTY. It indeed happens that I also use fcitx to type non-latin script from time to time (though in my understanding it should not be directly related to the compose key problem), with the following configuration:
<pre>export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS="@im=fcitx"
export XIM_PROGRAM=/usr/bin/fcitx</pre>
As I said, I do not think it is related though. I did try to switch fcitx off. Beware that although input programs like fcitx and ibus may provide an emulation for this feature, I am referring to the **X11** compose key.

Other GTK applications (like gvim) have no issue with the compose key.

**Comment by felmab** [comment] 2017-12-03 11:35
It works, thank you so much!

**Comment by felmab** [comment] 2017-12-03 12:04
Mmmh I noticed I can no longer type the '<' character, is this related?

**Comment by daa84** [comment] 2017-12-03 14:02
Hard to say, for me it works :smile: 
to enter '<' character in your keyboard layout do you use shift?

**Comment by daa84** [comment] 2017-12-03 14:24
Ups, sorry, yes, problem with '<' exists

**Comment by felmab** [comment] 2017-12-03 16:45
Great! Dead keys and '<' character work fine now, thanks again!

Now, sorry to be so picky, I think I might have found something else ^^; When I input CJK script (with fcitx), I can only insert one character at a time, e.g. (in pinyin mode):

- wo + <space> correctly inserts 我
- woele + <space> should insert 我饿了, but it inserts nothing.

This worked correctly before these last two commits, I've just checked with an older version on another machine.

**Comment by felmab** [comment] 2017-12-03 20:15
Cool, it is now working like a charm!

**Closed** 2017-12-04 12:24 UTC
