### ISSUE TITLE
Broken font rendering with pango 1.44

### ISSUE THREAD

**Issue by Teteros** [daa84/neovim-gtk#208] opened 2019-07-28 13:00 UTC
**Describe the bug**
It looks like pango 1.44 [deprecated](https://blogs.gnome.org/mclasen/2019/05/25/pango-future-directions/) Freetype and is using Harfbuzz [instead](https://gitlab.gnome.org/GNOME/pango/commit/fdd9e9e707e42131e7749d8674c59f57e0923a35).
However I have these rendering issues not only with bitmap/bdf/pcf fonts,
but also with ttf/otf so it may be something extra in neovim-gtk causing it.
![pango144](https://user-images.githubusercontent.com/5067989/62006968-be94f580-b13f-11e9-94ec-2b09c3070ba4.gif)

Rolling back to pango 1.43 fixes the issue.

**Technical information (please complete the following information):**
 - OS: Arch Linux x64
 - Neovim version: v0.3.8
 - Neovim-Gtk build version: master (6b0687d080b5959cd41073f131cc8539ea7d96ef)

**Comment by GorrillaRibs** [comment] 2019-07-29 05:10
Having the same issue, with the same packages on archlinux

**Comment by erlanger** [comment] 2019-07-29 09:59
This broke neovim-gtk for me, big problem since I use it as daily driver

**Comment by daa84** [comment] 2019-07-29 14:00
Looks like some size calculation issues.

**Comment by fgrsnau** [comment] 2019-07-30 07:39
Additionally to what others already said, the output also looks "blocky", especially in visual model and in the status line.

This might be a problem with anti-aliasing on edges lying close to each other. I have no idea how the rendering is actually implemented, though. 

![2019-07-30-093344_3840x1080_scrot](https://user-images.githubusercontent.com/11267323/62109917-cd44ef00-b29c-11e9-8f28-b02c46da9d04.png)

**Comment by XVilka** [comment] 2019-07-30 15:27
You can also read about other Pango 1.44 changes here: https://blogs.gnome.org/mclasen/2019/07/27/more-text-rendering-updates/

**Comment by smolck** [comment] 2019-07-30 22:56
Any news/updates on a possible fix?

**Comment by daa84** [comment] 2019-07-31 12:59
Does 1.44 available on ubuntu? What easiest way to reproduce this?

**Comment by smolck** [comment] 2019-07-31 16:47
@daa84 Not sure about ubuntu (you might be able to update to 1.44 by adding a new apt repo that contains the latest version, but that's a guess) since I use Arch, but to reproduce it all you need to do is download latest pango and start using neovim-gtk. Scroll around a file, type some text, etc.; you'll see multiple issues resulting from the pango update.

**Comment by erlanger** [comment] 2019-07-31 18:53
The problem is really bad, because you can't read the text after a few lines (I run the shell from neovim-gtk also). The best I would suggest is to setup an archlinux virtual machine and run it there after updating all the packages. You will see the problem right away.

It might be wise to keep this archlinux VM around, since you will get to know breakages like this very quickly before all the other distros.

**Comment by GorrillaRibs** [comment] 2019-08-01 01:12
In lieu of a fix for now (potentially until ubuntu gets an updated pango), pango-ubuntu from the AUR (and the related cairo & freetype libraries pulled as dependencies) seems fix the issue on Arch for the moment, and so far hasn't caused any other issues for me.

**Comment by smolck** [comment] 2019-08-01 02:21
Downgrading pango to v1.43 works for me on Arch. 

It may be a problem due to the change of no longer rounding glyph sizes or font metrics, at least in GNvim (another gtk-rs frontend for nvim which has the same sort of issues from the pango update).
See:
https://github.com/vhakulinen/gnvim/issues/84#issuecomment-517033841

**Comment by erlanger** [comment] 2019-08-03 20:56
Perhaps it has to do with this pango option: https://gitlab.gnome.org/GNOME/pango/commit/77b78746c901f95ca45a9ccffe9c32a38c0fb32b

**Comment by fgrsnau** [comment] 2019-08-05 11:34
[Pango 1.44.3 makes subpixel rounding optional](https://gitlab.gnome.org/GNOME/pango/blob/22dfeef4a26984ba81c6ff30117017dac372b706/NEWS#L4). Rounding glyphs to the integer grid is now the default again, see [this commit](https://gitlab.gnome.org/GNOME/pango/commit/77b78746c901f95ca45a9ccffe9c32a38c0fb32b). After upgrading, neovim-gtk looks better, but the visual position of the input cursor is off by roughly one character.

**Comment by erlanger** [comment] 2019-08-07 02:53
I still have serious problems with pango 1.44.3; they show up especially when running the terminal. As I press <enter> the lines start to get chopped off, and when I run `reset` in the shell, garbage remains on the terminal screen.

It is unusable. I am back to pango 1.43.

**Comment by erlanger** [comment] 2019-08-15 00:47
Still problems with pango 1.44.5, lines get chopped off in the termnal:
![pango](https://user-images.githubusercontent.com/8608855/63065593-27c58880-bef6-11e9-9c21-420eac3bbe88.png)

**Comment by smolck** [comment] 2019-09-08 13:46
The issue in GNvim seems to be that the values from `pango::Context.get_metrics()` are not being rounded (shouldn't they be?). In GNvim there is a workaround for the problems we've been seeing there which involves `ceil`'ing the values from `get_metrics`, see top of https://github.com/vhakulinen/gnvim/issues/85#issuecomment-527200720.

Thus, a workaround for Neovim-GTK might be modifying some lines [here in src/render/context.rs](https://github.com/daa84/neovim-gtk/blob/6e29fbaa3a30a02a2a7941b86b764b93ce0cc01b/src/render/context.rs#L115-L130) to call `ceil` the values like this (haven't actually tested this, and note the `ceil()` at the end of each line):

```rust
        CellMetrics {
            pango_ascent: font_metrics.get_ascent().ceil(),
            pango_descent: font_metrics.get_descent().ceil(),
            pango_char_width: font_metrics.get_approximate_digit_width().ceil(),
            ascent: (f64::from(font_metrics.get_ascent()) / f64::from(pango::SCALE)).ceil(),
            line_height: (f64::from(font_metrics.get_ascent() + font_metrics.get_descent())
                / f64::from(pango::SCALE)
                + f64::from(line_space)).ceil(),
            char_width: (f64::from(font_metrics.get_approximate_digit_width())
                / f64::from(pango::SCALE)).ceil(),
            underline_position: (f64::from(
                font_metrics.get_ascent() - font_metrics.get_underline_position(),
            ) / f64::from(pango::SCALE)).ceil(),
            underline_thickness: (f64::from(font_metrics.get_underline_thickness())
                / f64::from(pango::SCALE)).ceil(),
        }
    }
```

I feel there's more to it though, and I'll probably do some more extensive testing between pango v1.43 and v1.44 in GNvim (i.e. testing if the values given from `font_metrics.get_<whatever>()` is the same between the two versions of pango). It's possible (and probably likely) that the above is only masking the true issue. Hope it helps though.

**Comment by sebastien** [comment] 2019-11-26 04:54
Hey guys, any status update on that one? It's pretty major, and I'm missing neovim-gtk!

**Comment by smolck** [comment] 2019-11-26 05:52
@sebastien This may be, at least partly, an upstream issue. See https://github.com/vhakulinen/gnvim/issues/85#issuecomment-529234291.

**Comment by jacobmischka** [comment] 2019-11-26 16:47
I just happened to open this up minutes after you pushed that commit, ha.

While it's slightly better, as I can actually use the editor for the most part now, things still aren't aligning quite perfectly and I've noticed a few artifacts every once in a while.

Thanks for your work on trying to fix this!

![Screenshot from 2019-11-26 10-47-41](https://user-images.githubusercontent.com/3939997/69654321-31ed3c00-103a-11ea-9209-0ad4332faa68.png)

**Comment by sebastien** [comment] 2019-11-26 22:22
I also confirm that the pango_144_fix branch solves the issue for me, I couldn't stop any display glitch from a cursory look. Thanks a lot!

**Comment by daa84** [comment] 2019-11-29 16:32
Fix merged to master

**Closed by daa84** 2019-11-29 16:32 UTC

**Comment by GorrillaRibs** [comment] 2019-11-29 22:01
I know this is closed, but I'm still having cursor/statusline redraw issues with the current master on arch (the statusline/tabline take a long time to update, cursor isn't drawn when moving lines up/down quickly). Could this be introduced by a still-newer version of pango? (1.44-7 currently on arch)

**Comment by smolck** [comment] 2019-11-29 22:37
@GorrillaRibs I don't think your version of pango is the problem. Pango 1.44 has introduced a bunch of issues (as seen by this issue) that AFAIK haven't all been fixed. You might still want to try an earlier version of pango (in the 1.44 range) from the Arch Linux Archive to see if the latest version is the problem.

@sebastien Are you still getting problems with latest master of neovim-gtk?

**Comment by last-partizan** [comment] 2019-11-29 23:22
```
> yay -Q neovim-gtk-git pango
neovim-gtk-git 707-1
pango 1:1.44.7-1
```

I just updated pango and neovim-gtk, looks like issue is fixed for me.

**Comment by YaLTeR** [comment] 2019-11-30 07:27
Seems fixed here too!

**Comment by alerque** [comment] 2019-11-30 11:21
@GorrillaRibs I'm on Arch Linux as well with fully up do date packages (including Pango 1.44.7). I just compiled the AUR package for neovim-gtk-git a few minutes ago when I saw this bug was closed at it looks perfect for me. I threw a few big files at it and my full Airline setup and it seems to be doing fine. I don't see any alignment or cursor problems at all now, which is amazing considering the mess it was up until this got fixed.

**Comment by felmab** [comment] 2019-11-30 11:33
@alerque @GorrillaRibs same configuration, and it works pretty well.

**Comment by GorrillaRibs** [comment] 2019-11-30 19:51
Good to know, seems like there's something messed on my system specifically then (possibly related to using nvidia's PRIME offloading on a laptop? Font hinting/antialiasing?). I'll see what I can dig up, and update if I solve it. Thanks!

**Comment by GorrillaRibs** [comment] 2019-11-30 20:54
![nvim](https://user-images.githubusercontent.com/16048044/69905958-9fc29c00-1389-11ea-82de-2e82856ff52d.gif)
Attaching a gif of the strangeness in case there's something obvious I'm missing

**Comment by jacobmischka** [comment] 2019-11-30 21:00
Also can confirm that it's fixed on Arch. Thanks so much!

**Comment by alerque** [comment] 2019-11-30 21:03
@GorrillaRibs What your describing and I see in that screen shot is a completely different problem than what we've been tracking in this issue. You should open a separate issue for it. You do have a display glitch but it's unrelated.

**Comment by GorrillaRibs** [comment] 2019-11-30 21:24
@alerque You're right, I think I just assumed it was related as it looks similar to some of the glitches I was seeing before. I'll see if I can narrow down the issue first (try on wayland vs. xorg, other window managers) before I open an issue so we have an idea what to fix.

**Comment by sebastien** [comment] 2019-11-30 22:17
@smolck seems to be working now, I don't see the issues that I had before. Thanks *a lot*!

**Comment by erlanger** [comment] 2019-12-01 04:37
This solved it for me, even using Fira Code, but I've switched to kitty+nvim since.
