### ISSUE TITLE
Neovim-gtk flickers a lot

### ISSUE THREAD

**Issue by glacambre** [daa84/neovim-gtk#57] opened 2018-02-12 16:33 UTC
Hi,
I'm trying to run neovim-gtk on my computer (Linux 4.14, Debian, X11, integrated GPU) and it flickers a lot. I tried running neovim-gtk with an empty init.vim and also making the window smaller, nothing changed.
The only way to make the flickering stop on my computer is to focus another window.

I don't really know how to troubleshoot this issue, if you need more information, feel free to ask.

Pretty cool project by the way ! :)

**Comment by daa84** [comment] 2018-02-13 07:56
From description looks like cursor repaint produce flicker, as when window not in focus - cursor stops.
Flickering can happens when double buffer is disabled, but by default it must be enabled.

**Comment by unclechu** [comment] 2018-02-16 21:19
I have the same issue when I open *vim-ctrlspace* window, since I started to use neovim-gtk, I've never reported it because I haven't found a way to simply reproduce it. I tried to make clean `init.vim` with only *vim-ctrlspace* but in this case this flickering isn't happening, so I think it's not related to just *vim-ctrlspace*. Here is my config: https://github.com/unclechu/neovimrc

**Comment by unclechu** [comment] 2018-02-16 21:25
I just recorded a screencast that demonstrates flickering when I open *vim-ctrlspace* window:
https://www.youtube.com/watch?v=uqoUnieAdg8

**Comment by unclechu** [comment] 2018-02-16 21:28
Sometimes it's getting worse, on this video it's quite better that usual. Sometimes this happens even without opening *vim-ctrlspace* window, and even if I restart *neovim-gtk* it still happens. When this happens I just open TUI and go back to *neovim-gtk* after some time and this at least again happens only with *vim-ctrlspace* window (looks like some black magic).

**Comment by unclechu** [comment] 2018-02-22 10:04
@daa84 I just realized it happens during cursor blinking animation. I just met a moment when this blinking was at its worst rate and I see that in pauses of cursor blinking animation whole screen isn't blinking.

**Comment by unclechu** [comment] 2018-02-22 10:46
@daa84 look at my dirty hotfix to test it with cursor without blinking:
https://github.com/daa84/neovim-gtk/compare/master...unclechu:dirty-fix/cursor-without-animation?expand=1
It just gets it better, not heals it completely, I still got flickering when I move selection in list of buffers in *vim-ctrlspace* but when I'm not touching anything it stills without flickering.
See screencast: https://youtu.be/dgXCopYP7N0

P.S. Maybe it would be a good idea to add an command-line option to disable cursor animation, not just in sense of this issue but as an option for a user.

**Comment by daa84** [comment] 2018-02-23 10:26
The big question is why so strange thing happens? Gtk by default have double buffering enabled. So it can be just some nvim blinking.
Can you run `RUST_LOG=nvim_gtk::shell cargo run` to check logs, maybe some resize events come when flickering happens?
Another way i can try is to do double buffering by hand with cairo surface. Maybe in some environments double buffer is disabled by default

**Comment by daa84** [comment] 2018-02-23 17:59
Created test branch with double buffering through second cairo surface.
https://github.com/daa84/neovim-gtk/tree/double_buffer
@unclechu can you test this branch?
Solution is a bit dirty, but i want to find  problem source.

**Comment by unclechu** [comment] 2018-02-23 19:01
@daa84 I'll try this branch soon.

**Comment by unclechu** [comment] 2018-02-23 19:12
@daa84 Wow, now everything is fine, I see no flickering at all, it works. Thanks, I'll use this branch for now!

**Comment by unclechu** [comment] 2018-02-23 19:13
I could record a screencast if you need it that proves that it works.

**Comment by daa84** [comment] 2018-02-24 08:14
strange, i always think that gtk do double buffering for cairo automatically. But looks like in some cases it does not. Can you write your configuration? wayland/xorg, video driver?

Current double buffer solution think bad for performance. Later i adapt this changes better way.

**Comment by glacambre** [comment] 2018-02-24 14:06
@daa84 The double_buffer branch fixes the flickering on my end too!
Running `RUST_LOG=nvim_gtk::shell cargo run` on the master branch doesn't produce any output.

Here are bits of information about my configuration I found in my X11 log in case you need it.
```
Matched modesetting as autoconfigured driver 0
Matched fbdev as autoconfigured driver 1
Matched vesa as autoconfigured driver 2
Assigned the driver to the xf86ConfigLayout
Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
Loading /usr/lib/xorg/modules/drivers/fbdev_drv.so
Loading /usr/lib/xorg/modules/drivers/vesa_drv.so
FBDEV: driver for framebuffer: fbdev
VESA: driver for VESA chipsets: vesa
glamor: OpenGL accelerated X.org driver based.
modeset(0): [DRI2]   DRI driver: i965
modeset(0): [DRI2]   VDPAU driver: i965
```

I run the i3 window manager without a compositor if that makes a difference.

Thank you for fixing this bug!

**Comment by unclechu** [comment] 2018-02-24 22:38
@daa84 You could add an command-line option to disable double-buffering for users who could have performance issues.

**Comment by unclechu** [comment] 2018-02-24 22:44
Anyway, I think some usually unnoticeable performance issues (I personally haven't noticed any lags) is better than issues with my eyes. Maybe it would be good idea to ask about that in issues of package that provides it? I think it's here: https://github.com/gtk-rs/cairo/issues

**Comment by akatrevorjay** [comment] 2018-03-01 09:05
I noticed this too. Glad there's a fix here now.
New laptop with 120hz display; nvidia proprietary driver.

@unclechu Is your display by chance > 60hz?

**Comment by akatrevorjay** [comment] 2018-03-01 09:09
So, the branch at least for me only removes ~90% of the flickering, but it still happens every few seconds, especially during redraw upon move.

**Comment by akatrevorjay** [comment] 2018-03-01 09:47
Actually now it stopped flickering at all. Kudos +42

**Comment by unclechu** [comment] 2018-03-01 09:50
@akatrevorjay That it is still flickering a bit could be some tearing caused by your proprietary video driver. Which DE do you use? You could try some composite manager with vsync feature as attempt to fix it (such as [compton](https://github.com/chjj/compton)).

**Comment by akatrevorjay** [comment] 2018-03-02 00:17
@unclechu I use compton already :)

**Comment by unclechu** [comment] 2018-04-01 09:24
@daa84 Isn't that fix for double-buffering already in master branch (I'm just asking if I still urged to use separated branch or could try fresh *master*)?

**Comment by daa84** [comment] 2018-04-01 09:37
no, it still not merged.
As this fix slowdown rendering i plan to introduce env variable that will switch double buffering behavior (by default it will be disabled). As not all user have such problems with flickering.

**Comment by daa84** [comment] 2018-04-01 10:11
merged fix to master, by default disabled,
environment variable `NVIM_GTK_DOUBLE_BUFFER=1` can be used to enable it

maybe later i remove it, if this buffer will be used for some other functionality.

**Closed by daa84** 2018-04-01 10:11 UTC

**Comment by unclechu** [comment] 2018-04-03 21:38
Thanks!

**Comment by unclechu** [comment] 2018-06-18 20:05
@daa84 Now by using 0524e97b8ab1fc2207abb3e827fa7c5cff9207b3 I see this is fixed, I'm using **neovim-gtk** without this environment variable hack and don't see any flickering. Thanks a lot!
